### ISSUE TITLE
version_sync fails to parse toml blocks when inside blockquotes 

### ISSUE THREAD

**Issue by CreepySkeleton** [mgeisler/version-sync#83]
This part of a readme
~~~markdown
> This is a blockquote
>
> ```toml
> clap = { git = "https://github.com/clap-rs/clap/" }
> ```
~~~

fails with 
```
README.md (line 22) ... TOML parse error: unexpected character found: `>` at line 1 column 1 in
    > clap = { git = "https://github.com/clap-rs/clap/" }
```

I'm not sure if it's a bug in your crate or in `pulldown-cmark`.

As a workaround, would you be wiling to accept a PR that strips any leading `>` from `toml` blocks?

**Comment by mgeisler** [comment]
Thanks very much for reporting this! It's a bug in my library... I'm working on a fix right now.

**Comment by CreepySkeleton** [comment]
Thank you for the crate and the fix! It's very helpful 👍
