### ISSUE TITLE
Release update to crates.io with syn 1.0

### ISSUE THREAD

**Issue by lopopolo** [mgeisler/version-sync#84]
Hi @mgeisler, I was hoping you could push a new release to crates.io that includes https://github.com/mgeisler/version-sync/pull/80.

`version-sync` is the only dependency in my tree which pulls in pre-1.0 `syn` and `proc-macro2`. This increases compile times for my projects that use `version-sync`.

**Comment by mgeisler** [comment]
Hey @lopopolo Thanks for reminding me! I'll push out a new version later today with updated dependencies.

**Comment by mgeisler** [comment]
I've just pushed version 0.9.0 with updated dependencies to crates.io.
